ROUNDS_PER_GAME = 3

START_INT = 1
END_INT = 100

PROGRESSION_LEN_INTERVAL = (5, 10)
PROGRESSION_STEP_INTERVAL = (-10, 10)

__all__ = [
    'ROUNDS_PER_GAME',
    'START_INT',
    'END_INT',
    'PROGRESSION_LEN_INTERVAL',
    'PROGRESSION_STEP_INTERVAL',
]
